<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Asyncio: Proactor ConnectPipe() Race Condition â€” Victor Stinner blog 3</title>
	<meta name="description" content="Title: Asyncio: Proactor ConnectPipe() Race Condition; Date: 2019-01-30; Author: Victor Stinner">
	<meta name="author" content="Victor Stinner">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
		<script src="https://vstinner.github.io/theme/html5.js"></script>
		<![endif]-->
	<link href="https://vstinner.github.io/theme/css/ipython.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/simplex/bootstrap.min.css" rel="stylesheet">
	<link href="https://vstinner.github.io/theme/css/local.css" rel="stylesheet">
	<link href="https://vstinner.github.io/theme/css/pygments.css" rel="stylesheet">
</head>
<body>
<div class="container">
	<div class="page-header">
		<h1><a href="https://vstinner.github.io/">Victor Stinner blog 3</a>
			<br>	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
<div class="article" itemscope itemtype="http://schema.org/BlogPosting">
	<div class="text-center article-header">
		<h1 itemprop="name headline" class="article-title">Asyncio: Proactor ConnectPipe() Race Condition</h1>
		<span itemprop="author" itemscope itemtype="http://schema.org/Person">
			<h4 itemprop="name">Victor Stinner</h4>
		</span>
		<time datetime="2019-01-30T18:00:00+01:00" itemprop="datePublished">Wed 30 January 2019</time>
	</div>
	<div>
		Category:
		<span itemprop="articleSection">
			<a href="https://vstinner.github.io/category/cpython.html" rel="category">cpython</a>
		</span>
	</div>
 
	<div>
		Tags:
		<span itemprop="keywords">
			<a href="https://vstinner.github.io/tag/asyncio.html" rel="tag">asyncio</a>
		</span>
	</div>
	<div itemprop="articleBody" class="article-body"><a class="reference external image-reference" href="https://www.flickr.com/photos/phrawr/7612947262/"><img alt="Pipes" src="https://vstinner.github.io/images/pipes.jpg" /></a>
<p>Between December 2014 and January 2015, once I succeeded to fix the root issue
of the random asyncio crashes on Windows (<a class="reference external" href="https://vstinner.github.io/asyncio-proactor-cancellation-from-hell.html">Proactor Cancellation From Hell</a>), I fixed more race conditions
and bugs in <tt class="docutils literal">ProactorEventLoop</tt>:</p>
<ul class="simple">
<li><tt class="docutils literal">ConnectPipe()</tt> Race Condition</li>
<li>Race Condition in <tt class="docutils literal">BaseSubprocessTransport._try_finish()</tt></li>
<li>Close the transport on failure: ResourceWarning</li>
<li>Cleanup code handling pipes</li>
</ul>
<p>Previous article: <a class="reference external" href="https://vstinner.github.io/asyncio-proactor-cancellation-from-hell.html">Proactor Cancellation From Hell</a>. Next article:
<a class="reference external" href="https://vstinner.github.io/asyncio-proactor-wsarecv-cancellation-data-loss.html">asyncio: WSARecv() cancellation causing data loss</a>.</p>
<div class="section" id="connectpipe-race-condition">
<h2>ConnectPipe() Race Condition</h2>
<p>Once I succeeded to fix the root issue of the random asyncio crashes on Windows
(<a class="reference external" href="https://vstinner.github.io/asyncio-proactor-cancellation-from-hell.html">Proactor Cancellation From Hell</a>), I started to look at the
ConnectPipe special case: <a class="reference external" href="https://github.com/python/asyncio/issues/204">asyncio issue #204: Investigate
IocpProactor.accept_pipe() special case (don't register overlapped)</a> (issue created at 25 Aug
2014).</p>
<p>At January 21, 2015, I opened <a class="reference external" href="https://bugs.python.org/issue23293">bpo-23293: race condition related to
IocpProactor.connect_pipe()</a>.</p>
<p>While fixing <a class="reference external" href="https://bugs.python.org/issue23095">bpo-23095 (race condition when cancelling a _WaitHandleFuture)</a>, I saw that
<tt class="docutils literal">IocpProactor.connect_pipe()</tt> causes &quot;GetQueuedCompletionStatus() returned an
unexpected event&quot; messages to be logged, but also to hang the test suite.</p>
<p><tt class="docutils literal">IocpProactor._register()</tt> contains the comment:</p>
<pre class="literal-block">
# Even if GetOverlappedResult() was called, we have to wait for the
# notification of the completion in GetQueuedCompletionStatus().
# Register the overlapped operation to keep a reference to the
# OVERLAPPED object, otherwise the memory is freed and Windows may
# read uninitialized memory.
#
# For an unknown reason, ConnectNamedPipe() behaves differently:
# the completion is not notified by GetOverlappedResult() if we
# already called GetOverlappedResult(). For this specific case, we
# don't expect notification (register is set to False).
</pre>
<p><tt class="docutils literal">IocpProactor.close()</tt> contains this comment:</p>
<pre class="literal-block">
# The operation was started with connect_pipe() which
# queues a task to Windows' thread pool.  This cannot
# be cancelled, so just forget it.
</pre>
<p><tt class="docutils literal">IocpProactor.connect_pipe()</tt> is implemented with <tt class="docutils literal">QueueUserWorkItem()</tt>
which <strong>starts a thread that cannot be interrupted</strong>. Because of that, this
function requires special cases in <tt class="docutils literal">_register()</tt> and <tt class="docutils literal">close()</tt> methods of
<tt class="docutils literal">IocpProactor</tt>.</p>
<p>I proposed a solution to reimplement <tt class="docutils literal">IocpProactor.connect_pipe()</tt> <strong>without
a thread</strong>: <a class="reference external" href="https://code.google.com/p/tulip/issues/detail?id=197">asyncio issue #197: Rewrite IocpProactor.connect_pipe() with
non-blocking calls to avoid non interruptible QueueUserWorkItem()</a>.</p>
<p>At January 22, 2015, I pushed <a class="reference external" href="https://github.com/python/cpython/commit/7ffa2c5fdda8a9cc254edf67c4458b15db1252fa">commit 7ffa2c5f</a>:</p>
<pre class="literal-block">
commit 7ffa2c5fdda8a9cc254edf67c4458b15db1252fa
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Thu Jan 22 22:55:08 2015 +0100

    Issue #23293, asyncio: Rewrite IocpProactor.connect_pipe()
</pre>
<p>The change adds <tt class="docutils literal">_overlapped.ConnectPipe()</tt> which tries to connect to the
pipe for asynchronous I/O (overlapped): <strong>call CreateFile() in a loop until
it doesn't fail with ERROR_PIPE_BUSY</strong>. Use an increasing delay between 1 ms
and 100 ms.</p>
</div>
<div class="section" id="race-condition-in-basesubprocesstransport-try-finish">
<h2>Race Condition in BaseSubprocessTransport._try_finish()</h2>
<p>If the process exited before the <tt class="docutils literal">_post_init()</tt> method was called, scheduling
the call to <tt class="docutils literal">_call_connection_lost()</tt> with <tt class="docutils literal">call_soon()</tt> is wrong:
<tt class="docutils literal">connection_made()</tt> must be called before <tt class="docutils literal">connection_lost()</tt>.</p>
<p>Reuse the <tt class="docutils literal">BaseSubprocessTransport._call()</tt> method to schedule the call to
<tt class="docutils literal">_call_connection_lost()</tt> to ensure that <tt class="docutils literal">connection_made()</tt> and
<tt class="docutils literal">connection_lost()</tt> are called in the correct order.</p>
<p>At Dec 18, 2014, I pushed <a class="reference external" href="https://github.com/python/cpython/commit/1b9763d0a9c62c13dc2a06770032e5906b610c96">commit 1b9763d0</a>.
The explanation is long, but the change is basically a single line change,
extract:</p>
<pre class="literal-block">
- self._loop.call_soon(self._call_connection_lost, None)
+ self._call(self._call_connection_lost, None)
</pre>
<p><strong>Ordering properly callbacks in asyncio is challenging!</strong> The order matters
for the semantics of asyncio: it is part of the design of the <a class="reference external" href="https://www.python.org/dev/peps/pep-3156/">PEP 3156 --
Asynchronous IO Support Rebooted: the &quot;asyncio&quot; Module</a>.</p>
</div>
<div class="section" id="close-the-transport-on-failure-resourcewarning">
<h2>Close the transport on failure: ResourceWarning</h2>
<p>At January 15, 2015, I pushed <a class="reference external" href="https://github.com/python/cpython/commit/4bf22e033e975f61c33752db5a3764dc0f7d0b03">commit 4bf22e03</a>,
extract:</p>
<pre class="literal-block">
-  yield from transp._post_init()
+  try:
+      yield from transp._post_init()
+  except:
+      transp.close()
+      raise
</pre>
<p>Later, I will spend a lot of time (push many more changes) to ensure that
resources are properly released (especially close transports on failure,
similar to this change).</p>
<p>I will add many <strong>ResourceWarnings</strong> warnings in destructors when a transport,
subprocess or event loop is not closed explicitly.</p>
<p>For example, notice the <tt class="docutils literal">ResourceWarnings</tt> in the current destructor of
<tt class="docutils literal">_SelectorTransport</tt>:</p>
<pre class="literal-block">
class _SelectorTransport(transports._FlowControlMixin,
                         transports.Transport):

    def __del__(self, _warn=warnings.warn):
        if self._sock is not None:
            _warn(f&quot;unclosed transport {self!r}&quot;, ResourceWarning, source=self)
            self._sock.close()
</pre>
<p>I even enhanced Python 3.6 to be able to provide the <strong>traceback where the
leaked resource has been allocated</strong> thanks to my <tt class="docutils literal">tracemalloc</tt> module.
Example with <tt class="docutils literal">filebug.py</tt>:</p>
<pre class="literal-block">
def func():
    f = open(__file__)
    f = None

func()
</pre>
<p>Output with Python 3.6:</p>
<pre class="literal-block">
$ python3 -Wd -X tracemalloc=5 filebug.py
filebug.py:3: ResourceWarning: unclosed file &lt;_io.TextIOWrapper name='filebug.py' mode='r' encoding='UTF-8'&gt;
  f = None
Object allocated at (most recent call first):
  File &quot;filebug.py&quot;, lineno 2
    f = open(__file__)
  File &quot;filebug.py&quot;, lineno 5
    func()
</pre>
<p>The line where the warning is emitted is usually useless to understand the bug,
whereas the traceback is very useful to identify the leaked resource.</p>
<p>See <a class="reference external" href="https://pythondev.readthedocs.io/debug_tools.html#resourcewarning">my ResourceWarning documentation</a>.</p>
</div>
<div class="section" id="cleanup-code-handling-pipes">
<h2>Cleanup code handling pipes</h2>
<p>Thanks to the new implementation of <tt class="docutils literal">connect_pipe()</tt>, I was able to push
changes to simplify the code and remove various hacks in code handling pipes.</p>
<p><a class="reference external" href="https://github.com/python/cpython/commit/2b77c5467f376257ae22cbfbcb3a0e5e6349e92d">commit 2b77c546</a>:</p>
<pre class="literal-block">
commit 2b77c5467f376257ae22cbfbcb3a0e5e6349e92d
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Thu Jan 22 23:50:03 2015 +0100

    asyncio, Tulip issue 204: Fix IocpProactor.accept_pipe()

    Overlapped.ConnectNamedPipe() now returns a boolean: True if the pipe is
    connected (if ConnectNamedPipe() failed with ERROR_PIPE_CONNECTED), False if
    the connection is in progress.

    This change removes multiple hacks in IocpProactor.
</pre>
<p><a class="reference external" href="https://github.com/python/cpython/commit/3d2256f671b7ed5c769dd34b27ae597cbc69047c">commit 3d2256f6</a>:</p>
<pre class="literal-block">
commit 3d2256f671b7ed5c769dd34b27ae597cbc69047c
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Mon Jan 26 11:02:59 2015 +0100

    Issue #23293, asyncio: Cleanup IocpProactor.close()

    The special case for connect_pipe() is not more needed. connect_pipe() doesn't
    use overlapped operations anymore.
</pre>
<p><a class="reference external" href="https://github.com/python/cpython/commit/a19b7b3fcafe52b98245e14466ffc4d6750ca4f1">commit a19b7b3f</a>:</p>
<pre class="literal-block">
commit a19b7b3fcafe52b98245e14466ffc4d6750ca4f1
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Mon Jan 26 15:03:20 2015 +0100

    asyncio: Fix ProactorEventLoop.start_serving_pipe()

    If a client connected before the server was closed: drop the client (close the
    pipe) and exit.
</pre>
<p><a class="reference external" href="https://github.com/python/cpython/commit/e0fd157ba0cc92e435e7520b4ff641ca68d72244">commit e0fd157b</a>:</p>
<pre class="literal-block">
commit e0fd157ba0cc92e435e7520b4ff641ca68d72244
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Mon Jan 26 15:04:03 2015 +0100

    Issue #23293, asyncio: Rewrite IocpProactor.connect_pipe() as a coroutine

    Use a coroutine with asyncio.sleep() instead of call_later() to ensure that the
    schedule call is cancelled.

    Add also a unit test cancelling connect_pipe().
</pre>
<p><a class="reference external" href="https://github.com/python/cpython/commit/41063d2a59a24e257cd9ce62137e36c862e3ab1e">commit 41063d2a</a>:</p>
<pre class="literal-block">
commit 41063d2a59a24e257cd9ce62137e36c862e3ab1e
Author: Victor Stinner &lt;victor.stinner&#64;gmail.com&gt;
Date:   Mon Jan 26 22:30:49 2015 +0100

    asyncio, Tulip issue 204: Fix IocpProactor.recv()

    If ReadFile() fails with ERROR_BROKEN_PIPE, the operation is not pending: don't
    register the overlapped.

    I don't know if WSARecv() can fail with ERROR_BROKEN_PIPE. Since
    Overlapped.WSARecv() already handled ERROR_BROKEN_PIPE, let me guess that it
    has the same behaviour than ReadFile().
</pre>
</div>
</div>
	<hr>
	<h2>Comments</h2>
</div>
		</div>
	</div> 	<!-- <hr> -->
</div> <!-- /container -->
<footer class="aw-footer bg-danger">
	<div class="container"> <!-- footer -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="row">
					<div class="col-md-3">
						<h4>Navigation</h4>
						<ul class="list-unstyled my-list-style">
							<li><a href="https://vstinner.github.io">Victor Stinner blog 3</a></li>
							<li><a href="https://vstinner.github.io/feeds/all.atom.xml" type="application/atom+xml"><i class="fa fa-rss "></i> atom</a></li>
						</ul>
					</div>
					<div class="col-md-3">
						<h4>Author</h4>
						<ul class="list-unstyled my-list-style">
							<li><a href="https://twitter.com/VictorStinner">Follow @VictorStinner on Twitter</a></li>
						</ul>
					</div>
					<div class="col-md-3">
						<h4>Categories</h4>
						<ul class="list-unstyled my-list-style">
							<li><a href="https://vstinner.github.io/category/benchmark.html">benchmark (8)</a></li>
							<li><a href="https://vstinner.github.io/category/cpython.html">cpython (24)</a></li>
							<li><a href="https://vstinner.github.io/category/linux.html">linux (2)</a></li>
							<li><a href="https://vstinner.github.io/category/python.html">python (41)</a></li>
						</ul>
					</div>
					<div class="col-md-3">
						<h4>Links</h4>
						<ul class="list-unstyled my-list-style">
							<li><a href="http://vstinner.readthedocs.org/">Victor Stinner's Notes</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center center-block aw-bottom">
			<p>&copy; Victor Stinner 2016</p>
			<p>Powered by Pelican</p>
		</div>
	</div>
</div>
<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
	$("div.collapseheader").click(function () {
		$header = $(this).children("span").first();
		$codearea = $(this).children(".input_area");
		$codearea.slideToggle(500, function () {
			$header.text(function () {
				return $codearea.is(":visible") ? "Collapse Code" : "Expand Code";
			});
		});
	});
});
</script>
</body>
</html>